### ISSUE TITLE
Failing tests for pplane.poly

### ISSUE THREAD

**Issue by narc-Ontakac2** [gap-packages/polymaking#2]
[gap.txt](https://github.com/gap-packages/polymaking/files/5179569/gap.txt)

The tests for the pplane.poly file are failing. They are run with

	ln -s ../../.. debian/gaproot/pkg/polymaking
	gap -q -l "$(shell pwd)/debian/gaproot;/usr/share/gap" < tst/testall.g | tee debian/gap.txt

from a debian/rules Makefile. and produce the attached gap.txt file.

This happens with 0.8.2 using polymake 3.2r4-4 (debian) and gap 4r10p0-7 (debian).

**Comment by fingolfin** [comment]
See comments in #3
