### ISSUE TITLE
Not compatible with polymake 4.1

### ISSUE THREAD

**Issue by narc-Ontakac2** [gap-packages/polymaking#3]
ap -q -l "/home/jo/projects/gap-hap/gap-polymaking_0.8.2/debian/gaproot;/usr/share/gap" < tst/testall.g | tee debian/gap.tst
true
Architecture: x86_64-pc-linux-gnu-default64-kv7

testing: /home/jo/projects/gap-hap/gap-polymaking_0.8.2/debian/gaproot/pkg/polymaking/tst/polymaking.tst
usage: polymake [-dv] [-A|-a <application>]
                [--reconfigure] [--config-path PATH ... | --no-config | --ignore-config]
                [ --script | --iscript <script_file> arg ... ] | script_file | 'one-liner' |
                - | [ --connect SOCKETFILE | HOST:PORT ] |
                --touch <file> ... | --help | --version

All tests fail on debian testing with polymake 4.1. The above error message seems to indicate a change in command line usage.

**Comment by narc-Ontakac2** [comment]
It seems polymake has given up the compatibility mode, [see](https://polymake.org/doku.php/user_guide/tutorials/release/3.6/legacy)

**Comment by narc-Ontakac2** [comment]
The last test Polymake(plane, "DIMS") can not work anymore, since DIMS has been removed, [see](https://forum.polymake.org/viewtopic.php?t=553).

**Comment by fingolfin** [comment]
I am afraid nobody is available who is maintaining the "mathematical" side of this package, in particular nobody with any expertise or interest in using Polymake. The GAP team took over technical maintenance of this package only -- so we try to adapt this package to any changes made to GAP itself, and to accept PRs, and make new releases. But we cannot provide much assistance with this kind of problem, I am afraid.

Regarding DIMS, grepping the source of this package for "DIMS", I noticed a function `MapKeyWordToPolymakeFormat` which seems to be meant to deal with this kind of change:
```gap
InstallMethod(MapKeyWordToPolymakeFormat,"for PolymakeObject",[IsString],
###########
# This is a workaround for the next-generation polymake
# there we need to call keywords of the form "HASSE_DIAGRAM->FACES"
# and that does not work as an entry of a record. So we have do do
# some extra mapping (yes, it is a hack).
##
# direction of the mapping: GAP keyword mapped to polymake keyword
#######
InstallMethod(MapKeyWordToPolymakeFormat,"for PolymakeObject",[IsString],
        function(option)
	if option   = "FACES" then
	   return     "HASSE_DIAGRAM->FACES";
	elif option = "DIMS"  then 	   
	   return     "HASSE_DIAGRAM->DIMS";
	else
	   return option;	
	fi;
end);
```

But that is not enough to adapt to Polymake 4.x which dropped the "old" command line mode. Somebody would need to dig into this package and adapt it accordingly.

**Comment by narc-Ontakac2** [comment]
Concerning DIMS, this is not fixable with the mapping you found, this is already applied but HASSE_DIAGRAM->DIMS is not working [see](https://forum.polymake.org/viewtopic.php?t=553).

**Comment by narc-Ontakac2** [comment]
I have a purely technical fix. It does 3 things:
1. A compatibility perl script as suggested in [see](https://polymake.org/doku.php/user_guide/tutorials/release/4.1/legacy) is added.
2. Since files without application and type are no longer accepted a default of application polytope, type Polytope<Rational> is added to every file.
3. The test using DIMS is replaced by a test using FACETS.

**Comment by narc-Ontakac2** [comment]
The good news is that the polymake tests after patching still work with polymake 3.3.

**Comment by narc-Ontakac2** [comment]
More good news: The tests from HAPcryst succeed, if I add an "uptowhitespace".
