### ISSUE TITLE
VISUAL is not working

### ISSUE THREAD

**Issue by narc-Ontakac2** [gap-packages/polymaking#6]
This is due to the fact that this is an actual method call and not a property that can be retrieved by calling give.

Since VISUAL starts a web browser to display graphics it is hard to do automatic tests.

**Comment by alex-konovalov** [comment]
I see that CI tests pass - was this resolved somehow?

**Comment by narc-Ontakac2** [comment]
No, this is not covered by the tests. VISUAL starts a browser to display graphs.

**Comment by alex-konovalov** [comment]
Thanks, now I understand the issue :)

**Comment by alex-konovalov** [comment]
Fix in #9, needs reviewing - thanks @narc-Ontakac2.
