### ISSUE TITLE
new release please

### ISSUE THREAD

**Issue by grahamknockillaree** [gap-packages/polymaking#7]
@fingolfin  Please could you release v0.8.4 of Polymaking sometime when you have some time.  I've updated two files and PackageInfo.g, and the new release should allow HAP to pass all its tests.  Thanks.

**Comment by alex-konovalov** [comment]
Something went wrong:

```
* polymaking - new version 0.8.4 discovered!!!
  ============================================
  Getting new archives from 
  https://github.com/gap-packages/polymaking/releases/download/v0.8.4/polymaki\
ng-0.8.4[ ".tar.gz" ]
  unpacking polymaking-0.8.4.tar.gz
ERROR (polymaking): could not unpack archive .... SKIPPING !!!
```

Indeed, the webpage https://gap-packages.github.io/polymaking/ serves 0.8.3, but the file

https://gap-packages.github.io/polymaking/PackageInfo.g has 0.8.4.

This should not happen if ReleaseTools are used properly - it automates all steps and updates all gh-pages files in one commit.

**Comment by alex-konovalov** [comment]
Also this is wrong: https://github.com/gap-packages/polymaking/releases/tag/tagname - seems like failed attempt to create 0.8.4 tag.

**Comment by fingolfin** [comment]
I don't know what @grahamknockillaree exactly did, but it certainly went very wrong. In particular, it looks as only the `PackageInfo.g` file in the `gh-pages` branch was updated, but no tag was created, no tarballs uploaded, nor the rest of the website updated -- @grahamknockillaree did you really use the latest https://github.com/gap-system/ReleaseTools ?

Anyway, I've now re-run the release script, and it worked just fine. A test for the new `ADJACENCY` feature would have been nice, though, but perhaps someone can add one in the future.

**Comment by grahamknockillaree** [comment]
@fingolfin   Thanks.  I don't know what I did wrong either. I spent a couple of hours late last night trying to figure out what I did wrong but to no avail.  Maybe I should not attempt to update things so late at night. :)

**Comment by alex-konovalov** [comment]
Of course the consequence is that the package update system now knows `PackageInfo.g` for 0.8.4 which does not work, so it now rejects the new one:
```
Package: polymaking
  changed components: [ "Date" ]
  ERROR (polymaking): There are changed components in the new info file from
  https://gap-packages.github.io/polymaking/PackageInfo.g
   but .Version remains the same. This is not allowed, so the info file will n\
ot be changed
  PackageInfo.g is not accepted because of an error.
```
There are three ways to fix this:
a) for me manually go into the system and reset the cached `PackageInfo.g` to the old one for 0.8.3
b) make new release of 0.8.5
c) make release of 0.8.4 but with the same date.

(b) is the cleanest; (a) is OK; (c) is bad.

**Comment by grahamknockillaree** [comment]
If you'd like me to do (b) then please let me know.  I now have the most recent version of Release Tools so I can do this without messing things up!

I'll wait for instructions.

**Comment by alex-konovalov** [comment]
@grahamknockillaree please (b) then, this will not require any action from me and hence no delay. Also will give you a chance to practice ReleaseTools!
